### ISSUE TITLE
Yarn unable to install

### ISSUE THREAD

**Issue by lightninglu10** [UMNLibraries/react-citation#1]
Hey guys, this looks like an awesome library, but how do I install it with yarn?

I see the two latest commits you guys have made that address a yarn issue, but still not sure how to install this thing.

**Comment by lightninglu10** [comment]
also, when I try to install with the dist/react-citation.js file, I get a bunch of errors:

<img width="486" alt="screen shot 2017-08-01 at 5 25 22 pm" src="https://user-images.githubusercontent.com/2453737/28852504-6f5ab66e-76de-11e7-8fc9-fa95311d93a4.png">

**Comment by chadfennell** [comment]
Hi @lightninglu10,

Thanks for your feedback. I have updated the installation instructions and created an example project to demonstrate how to include react-citation in your project: https://github.com/UMNLibraries/react-citation-demo

I'll be refactoring this project in a couple of months, improving the overall code quality (this was one of my first react components) and replacing some of my custom code with react-router. 

So, do let me know if you run into any issues or feel like there are critical features missing. I'll hopefully be in a place be be a bit more responsive in the coming months.

**Comment by lightninglu10** [comment]
Hey @chadfennell , thanks for the quick response! 

I'm trying to install the package right now -- 

```
yarn add git+https://github.com/UMNLibraries/react-citation.git#51682c87e55bd
```

asks me to input an SSH password, and 

```
npm install --save git+https://github.com/UMNLibraries/react-citation.git
```

hangs.

Still not sure how I include this library into my project!

**Comment by lightninglu10** [comment]
Oh, just kidding...

So for anyone else who has this issue, it's actually asking you for YOUR own RSA key. So type in your password for your RSA Key! And each time it asks you twice.

Installed.
